[package]
name = "rust-rabbitmq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = { version = "1.0.5", features = ["traces"] }
serde = { version = "1.0.152", features = ["serde_derive"] }
serde_json = "1.0.91"
tokio = "1.25.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
