[package]
name = "rust-rabbitmq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = { version = "1.0.6", features = ["traces", "compliance_assert"] }
anyhow = "1.0.69"
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["serde_derive"] }
serde_json = "1.0.92"
thiserror = "1.0.38"
tokio = "1.25.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
